return {
	armpw = {
		buildpic = "ARMPW.DDS",
		buildtime = 1650,
		canmove = true,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "22 30 22",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 900,
		explodeas = "smallExplosionGeneric",
		footprintx = 2,
		footprintz = 2,
		health = 370,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.414,
		maxdec = 0.69,
		maxslope = 17,
		maxwaterdepth = 12,
		metalcost = 54,
		movementclass = "BOT3",
		nochasecategory = "VTOL",
		objectname = "Units/ARMPW.s3o",
		script = "Units/ARMPW.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 429,
		speed = 87,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.848,
		turnrate = 1214.40002,
		upright = true,
		customparams = {
			model_author = "Kaiser",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBots",
			unitgroup = "weapon",
			weapon1turretx = 300,
			weapon1turrety = 300,
			continuousaim_frames = 2,
			continuousaim_isspam = true,
			hasdeathanimation = true, -- ! has to be updated with unit script
			stompable = true,
		},
		data = {
			armordef = "standard",
			rename   = "armada_pawn",
			icontype = {
				bitmap = "icons/bot_t1_raid_0.7.png",
				size = 0.73499995
			},
			soundeffects = {
				BaseSoundSelectType = "arm-bot-tiny-sel",
				BaseSoundMovementType = "arm-bot-tiny-ok",
				BaseSoundWeaponType = "fastemgalt-small",
			},
			deferredlights = {
				headlightpw = {
					lightType = "cone",
					pieceName = "head",
					lightConfig = {
						posx = 0,
						posy = 2,
						posz = 1,
						radius = 50,
						dirx = 0,
						diry = -0.07,
						dirz = 1,
						theta = 0.29,
						r = 1,
						g = 1,
						b = 0.89,
						a = 0.55,
						modelfactor = -0.5,
						specular = -1.5,
						scattering = 1.8,
						lensflare = 1,
						lifetime = 0,
						sustain = 0,
						selfshadowing = 1
					},
				},
				eyes = {
					lightType = "point",
					pieceName = "head",
					lightConfig = {
						posx = 0,
						posy = 2.0,
						posz = 8.3,
						radius = 5,
						color2r = 0.6,
						color2g = 0.5,
						color2b = 0.4,
						colortime = 30,
						r = 1.2,
						g = 1,
						b = 0.25,
						a = 0.8,
						modelfactor = 0.8,
						specular = 0.3,
						scattering = 0.2,
						lensflare = 0,
						lifetime = 0,
						sustain = 0,
						selfshadowing = 0
					},
				},
				arm1 = {
					lightType = "point",
					pieceName = "lgun",
					lightConfig = {
						posx = 0,
						posy = 0,
						posz = 3.5,
						radius = 2,
						color2r = 1,
						color2g = 1,
						color2b = 0.25,
						colortime = 0,
						r = 1.2,
						g = 1,
						b = 0.25,
						a = 1,
						modelfactor = 0.8,
						specular = 0.6,
						scattering = 0.3,
						lensflare = 0,
						lifetime = 0,
						sustain = 0,
						selfshadowing = 0
					},
				},
				arm2 = {
					lightType = "point",
					pieceName = "rgun",
					lightConfig = {
						posx = 0,
						posy = 0,
						posz = 3.5,
						radius = 2,
						color2r = 1,
						color2g = 1,
						color2b = 0.25,
						colortime = 0,
						r = 1.2,
						g = 1,
						b = 0.25,
						a = 1,
						modelfactor = 0.8,
						specular = 0.6,
						scattering = 0.3,
						lensflare = 0,
						lifetime = 0,
						sustain = 0,
						selfshadowing = 0
					},
				},
				backpack1 = {
					lightType = "point",
					pieceName = "head",
					lightConfig = {
						posx = 4,
						posy = 3.5,
						posz = -8,
						radius = 3.5,
						color2r = 1,
						color2g = 1,
						color2b = 1,
						colortime = 0,
						r = -1,
						g = 1,
						b = 1,
						a = 2.5,
						modelfactor = 0.2,
						specular = 0.3,
						scattering = 0.2,
						lensflare = 0,
						lifetime = 0,
						sustain = 0,
						selfshadowing = 0
					},
				},
				backpack2 = {
					lightType = "point",
					pieceName = "head",
					lightConfig = {
						posx = -4,
						posy = 3.5,
						posz = -8,
						radius = 3.5,
						color2r = 1,
						color2g = 1,
						color2b = 1,
						colortime = 0,
						r = -1,
						g = 1,
						b = 1,
						a = 2.5,
						modelfactor = 0.2,
						specular = 0.3,
						scattering = 0.2,
						lensflare = 0,
						lifetime = 0,
						sustain = 0,
						selfshadowing = 0
					},
				},
			},
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0.979118347168 -0.453806965332 -0.796119689941",
				collisionvolumescales = "30.1392364502 18.4953460693 29.797164917",
				collisionvolumetype = "Box",
				damage = 192,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 40,
				metal = 29,
				object = "Units/armpw_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 96,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 12,
				object = "Units/arm2X2F.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-tiny",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg2",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servtny2",
			},
			select = {
				[1] = "servtny2",
			},
		},
		weapondefs = {
			emg = {
				areaofeffect = 8,
				avoidfeature = false,
				burst = 3,
				burstrate = 0.1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:plasmahit-small",
				firestarter = 100,
				impulsefactor = 0.123,
				intensity = 0.7,
				name = "Rapid-fire close-quarters g2g plasma guns",
				noselfdamage = true,
				range = 180,
				reloadtime = 0.3,
				rgbcolor = "1 0.95 0.4",
				size = 1.75,
				soundhitwet = "splshbig",
				soundstart = "flashemg",
				sprayangle = 1180,
				tolerance = 5000,
				turret = true,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 9,
					vtol = 3,
				},
				data = {
					deferredlights = {
						MuzzleFlash = {
							"Warm",
							"Medium",
							posx = 1,
							posy = 1,
							posz = 1,
							radius = 50,
							r = 1.2,
							g = 1.1,
							b = 1.0,
							a = 0.5,
							color2r = 0.3,
							color2g = 0.12,
							color2b = 0.05,
							colortime = 4,
							modelfactor = 0.5,
							specular = 0.3,
							scattering = 0.8,
							lensflare = 14,
							lifetime = 17,
							sustain = 2
						},
					},
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "EMG",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
